### ISSUE TITLE
Webpack CSS compilation error when running scripts/server.sh after scripts/update.sh on the split-modeling branch

### ISSUE THREAD

**Issue by jwalgran** [geotrellis/tree-prioritization-demo#160]
- Destroy any existing VM
- Run `scripts/setup.sh`
- `vagrant ssh` and run `scripts/update.sh` then `scripts/server.sh`

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ ./scripts/server.sh
Starting vagrant_app-frontend_1 ...
Starting vagrant_app-frontend_1
Starting vagrant_api-server_1 ...
Starting vagrant_app-frontend_1 ... done
Attaching to vagrant_api-server_1, vagrant_app-frontend_1
app-frontend_1  | yarn run v0.23.4
app-frontend_1  | $ node_modules/.bin/webpack-dev-server --config webpack.dev.config.js --inline --hot --progress --colors --host 0.0.0.0 --port 8286 --history-api-fallback
app-frontend_1  | webpack result is served from http://localhost:8286/
app-frontend_1  | content is served from /usr/src
app-frontend_1  | 404s will fallback to /index.html
app-frontend_1  | Version: webpack 1.15.0
app-frontend_1  | Time: 3018ms
app-frontend_1  |      Asset     Size  Chunks             Chunk Names
app-frontend_1  |    demo.js  1.85 MB       0  [emitted]  demo
app-frontend_1  | index.html  12.9 kB          [emitted]
app-frontend_1  | chunk    {0} demo.js (demo) 1.66 MB [rendered]
app-frontend_1  |     [0] multi demo 76 bytes {0} [built]
app-frontend_1  |     [1] (webpack)-dev-server/client?http://0.0.0.0:8286 4.16 kB {0} [built]
app-frontend_1  |     [2] node_modules/url/url.js 23.3 kB {0} [built]
app-frontend_1  |     [3] node_modules/punycode/punycode.js 14.7 kB {0} [built]
app-frontend_1  |     [4] node_modules/webpack/buildin/module.js 251 bytes {0} [built]
app-frontend_1  |     [5] node_modules/url/util.js 314 bytes {0} [built]
app-frontend_1  |     [6] node_modules/querystring/index.js 127 bytes {0} [built]
app-frontend_1  |     [7] node_modules/querystring/decode.js 2.4 kB {0} [built]
app-frontend_1  |     [8] node_modules/querystring/encode.js 2.09 kB {0} [built]
app-frontend_1  |     [9] node_modules/strip-ansi/index.js 161 bytes {0} [built]
app-frontend_1  |    [10] node_modules/ansi-regex/index.js 135 bytes {0} [built]
app-frontend_1  |    [11] (webpack)-dev-server/client/socket.js 897 bytes {0} [built]
app-frontend_1  |    [12] node_modules/sockjs-client/lib/entry.js 244 bytes {0} [built]
app-frontend_1  |    [13] node_modules/sockjs-client/lib/transport-list.js 613 bytes {0} [built]
app-frontend_1  |    [14] node_modules/sockjs-client/lib/transport/websocket.js 2.72 kB {0} [built]
app-frontend_1  |    [15] node_modules/process/browser.js 5.42 kB {0} [built]
app-frontend_1  |    [16] node_modules/sockjs-client/lib/utils/event.js 2 kB {0} [built]
app-frontend_1  |    [17] node_modules/sockjs-client/lib/utils/random.js 746 bytes {0} [built]
app-frontend_1  |    [18] node_modules/sockjs-client/lib/utils/browser-crypto.js 438 bytes {0} [built]
app-frontend_1  |    [19] node_modules/sockjs-client/lib/utils/url.js 975 bytes {0} [built]
app-frontend_1  |    [20] node_modules/url-parse/index.js 11.4 kB {0} [built]
app-frontend_1  |    [21] node_modules/requires-port/index.js 753 bytes {0} [built]
app-frontend_1  |    [22] node_modules/querystringify/index.js 1.51 kB {0} [built]
app-frontend_1  |    [23] node_modules/debug/src/browser.js 4.78 kB {0} [built]
app-frontend_1  |    [24] node_modules/debug/src/debug.js 4.39 kB {0} [built]
app-frontend_1  |    [25] node_modules/ms/index.js 2.72 kB {0} [built]
app-frontend_1  |    [26] node_modules/inherits/inherits_browser.js 672 bytes {0} [built]
app-frontend_1  |    [27] node_modules/sockjs-client/lib/event/emitter.js 1.27 kB {0} [built]
app-frontend_1  |    [28] node_modules/sockjs-client/lib/event/eventtarget.js 1.85 kB {0} [built]
app-frontend_1  |    [29] node_modules/sockjs-client/lib/transport/browser/websocket.js 210 bytes {0} [built]
app-frontend_1  |    [30] node_modules/sockjs-client/lib/transport/xhr-streaming.js 1.25 kB {0} [built]
app-frontend_1  |    [31] node_modules/sockjs-client/lib/transport/lib/ajax-based.js 1.31 kB {0} [built]
app-frontend_1  |    [32] node_modules/sockjs-client/lib/transport/lib/sender-receiver.js 1.18 kB {0} [built]
app-frontend_1  |    [33] node_modules/sockjs-client/lib/transport/lib/buffered-sender.js 2.3 kB {0} [built]
app-frontend_1  |    [34] node_modules/sockjs-client/lib/transport/lib/polling.js 1.32 kB {0} [built]
app-frontend_1  |    [35] node_modules/sockjs-client/lib/transport/receiver/xhr.js 1.58 kB {0} [built]
app-frontend_1  |    [36] node_modules/sockjs-client/lib/transport/sender/xhr-cors.js 343 bytes {0} [built]
app-frontend_1  |    [37] node_modules/sockjs-client/lib/transport/browser/abstract-xhr.js 4.8 kB {0} [built]
app-frontend_1  |    [38] node_modules/sockjs-client/lib/transport/sender/xhr-local.js 352 bytes {0} [built]
app-frontend_1  |    [39] node_modules/sockjs-client/lib/utils/browser.js 560 bytes {0} [built]
app-frontend_1  |    [40] node_modules/sockjs-client/lib/transport/xdr-streaming.js 984 bytes {0} [built]
app-frontend_1  |    [41] node_modules/sockjs-client/lib/transport/sender/xdr.js 2.46 kB {0} [built]
app-frontend_1  |    [42] node_modules/sockjs-client/lib/transport/eventsource.js 766 bytes {0} [built]
app-frontend_1  |    [43] node_modules/sockjs-client/lib/transport/receiver/eventsource.js 1.58 kB {0} [built]
app-frontend_1  |    [44] node_modules/sockjs-client/lib/transport/browser/eventsource.js 37 bytes {0} [built]
app-frontend_1  |    [45] node_modules/sockjs-client/lib/transport/lib/iframe-wrap.js 981 bytes {0} [built]
app-frontend_1  |    [46] node_modules/sockjs-client/lib/transport/iframe.js 3.83 kB {0} [built]
app-frontend_1  |    [47] node_modules/json3/lib/json3.js 43.3 kB {0} [built]
app-frontend_1  |    [48] (webpack)/buildin/amd-options.js 43 bytes {0} [built]
app-frontend_1  |    [49] node_modules/sockjs-client/lib/version.js 26 bytes {0} [built]
app-frontend_1  |    [50] node_modules/sockjs-client/lib/utils/iframe.js 5.03 kB {0} [built]
app-frontend_1  |    [51] node_modules/sockjs-client/lib/utils/object.js 532 bytes {0} [built]
app-frontend_1  |    [52] node_modules/sockjs-client/lib/transport/htmlfile.js 710 bytes {0} [built]
app-frontend_1  |    [53] node_modules/sockjs-client/lib/transport/receiver/htmlfile.js 2.2 kB {0} [built]
app-frontend_1  |    [54] node_modules/sockjs-client/lib/transport/xhr-polling.js 894 bytes {0} [built]
app-frontend_1  |    [55] node_modules/sockjs-client/lib/transport/xdr-polling.js 712 bytes {0} [built]
app-frontend_1  |    [56] node_modules/sockjs-client/lib/transport/jsonp-polling.js 1.02 kB {0} [built]
app-frontend_1  |    [57] node_modules/sockjs-client/lib/transport/receiver/jsonp.js 5.57 kB {0} [built]
app-frontend_1  |    [58] node_modules/sockjs-client/lib/transport/sender/jsonp.js 2.46 kB {0} [built]
app-frontend_1  |    [59] node_modules/sockjs-client/lib/main.js 11.9 kB {0} [built]
app-frontend_1  |    [60] node_modules/sockjs-client/lib/shims.js 17.2 kB {0} [built]
app-frontend_1  |    [61] node_modules/sockjs-client/lib/utils/escape.js 2.36 kB {0} [built]
app-frontend_1  |    [62] node_modules/sockjs-client/lib/utils/transport.js 1.35 kB {0} [built]
app-frontend_1  |    [63] node_modules/sockjs-client/lib/utils/log.js 450 bytes {0} [built]
app-frontend_1  |    [64] node_modules/sockjs-client/lib/event/event.js 477 bytes {0} [built]
app-frontend_1  |    [65] node_modules/sockjs-client/lib/location.js 177 bytes {0} [built]
app-frontend_1  |    [66] node_modules/sockjs-client/lib/event/close.js 295 bytes {0} [built]
app-frontend_1  |    [67] node_modules/sockjs-client/lib/event/trans-message.js 292 bytes {0} [built]
app-frontend_1  |    [68] node_modules/sockjs-client/lib/info-receiver.js 2.22 kB {0} [built]
app-frontend_1  |    [69] node_modules/sockjs-client/lib/transport/sender/xhr-fake.js 456 bytes {0} [built]
app-frontend_1  |    [70] node_modules/sockjs-client/lib/info-iframe.js 1.52 kB {0} [built]
app-frontend_1  |    [71] node_modules/sockjs-client/lib/info-iframe-receiver.js 791 bytes {0} [built]
app-frontend_1  |    [72] node_modules/sockjs-client/lib/info-ajax.js 1.03 kB {0} [built]
app-frontend_1  |    [73] node_modules/sockjs-client/lib/iframe-bootstrap.js 2.9 kB {0} [built]
app-frontend_1  |    [74] node_modules/sockjs-client/lib/facade.js 723 bytes {0} [built]
app-frontend_1  |    [75] node_modules/webpack/hot/dev-server.js 1.85 kB {0} [built]
app-frontend_1  |    [76] node_modules/webpack/hot/log-apply-result.js 813 bytes {0} [built]
app-frontend_1  |    [77] ./js/modeling/modeling.js 5.02 kB {0} [built] [1 error]
app-frontend_1  |    [78] ./js/vendor/jquery.js 273 kB {0} [built]
app-frontend_1  |    [79] ./~/webpack/buildin/module.js 251 bytes {0} [built]
app-frontend_1  |    [80] node_modules/leaflet/dist/leaflet-src.js 382 kB {0} [built]
app-frontend_1  |    [81] ./js/modeling/prioritization.js 18.4 kB {0} [built]
app-frontend_1  |    [82] node_modules/lodash/dist/lodash.compat.js 244 kB {0} [built]
app-frontend_1  |    [83] node_modules/baconjs/dist/Bacon.js 65.7 kB {0} [built]
app-frontend_1  |    [84] (webpack)/buildin/amd-define.js 85 bytes {0} [built]
app-frontend_1  |    [85] node_modules/ramda/ramda.js 172 kB {0} [built]
app-frontend_1  |    [86] ./js/shim/bootstrap-slider.js 10.9 kB {0} [built]
app-frontend_1  |    [87] ./js/modeling/controls.js 1.81 kB {0} [built]
app-frontend_1  |    [88] ./js/modeling/template.js 338 bytes {0} [built]
app-frontend_1  |    [89] ./js/modeling/prioritizationDropdowns.js 2.71 kB {0} [built]
app-frontend_1  |    [90] ./js/modeling/prioritizationPresets.js 1.03 kB {0} [built]
app-frontend_1  |    [91] ./js/modeling/locationMasks.js 1.98 kB {0} [built]
app-frontend_1  |    [92] ./js/modeling/otmTypeahead.js 11.3 kB {0} [built]
app-frontend_1  |    [93] ./js/shim/bootstrap.js 68.9 kB {0} [built]
app-frontend_1  |    [94] ./js/shim/typeahead.jquery.js 63.5 kB {0} [built]
app-frontend_1  |    [95] ./~/timers-browserify/main.js 1.36 kB {0} [built]
app-frontend_1  |    [96] node_modules/setimmediate/setImmediate.js 6.47 kB {0} [built]
app-frontend_1  |    [97] node_modules/mustache/mustache.js 15.1 kB {0} [built]
app-frontend_1  |    [98] ./js/vendor/bloodhound.js 33.2 kB {0} [built]
app-frontend_1  |    [99] ./js/modeling/baconUtils.js 6.57 kB {0} [built]
app-frontend_1  |   [101] node_modules/es6-promise/dist/es6-promise.js 28.5 kB {0} [built]
app-frontend_1  |   [103] node_modules/leaflet.gridlayer.googlemutant/Leaflet.GoogleMutant.js 12.5 kB {0} [built]
app-frontend_1  |   [104] node_modules/webpack-dev-server/client?http://localhost:8286/ 4.16 kB {0} [built]
app-frontend_1  |   [105] node_modules/webpack-dev-server/client/socket.js 897 bytes {0} [built]
app-frontend_1  |      + 1 hidden modules
app-frontend_1  |
app-frontend_1  | ERROR in ./assets/css/sass/main.scss
app-frontend_1  | Module build failed: Error: ENOENT: no such file or directory, scandir '/usr/src/node_modules/node-sass/vendor'
app-frontend_1  |     at Error (native)
app-frontend_1  |     at Object.fs.readdirSync (fs.js:952:18)
app-frontend_1  |     at Object.getInstalledBinaries (/usr/src/node_modules/node-sass/lib/extensions.js:121:13)
app-frontend_1  |     at foundBinariesList (/usr/src/node_modules/node-sass/lib/errors.js:20:15)
app-frontend_1  |     at foundBinaries (/usr/src/node_modules/node-sass/lib/errors.js:15:5)
app-frontend_1  |     at Object.module.exports.missingBinary (/usr/src/node_modules/node-sass/lib/errors.js:45:5)
app-frontend_1  |     at module.exports (/usr/src/node_modules/node-sass/lib/binding.js:15:30)
app-frontend_1  |     at Object.<anonymous> (/usr/src/node_modules/node-sass/lib/index.js:14:35)
app-frontend_1  |     at Module._compile (module.js:570:32)
app-frontend_1  |     at Object.Module._extensions..js (module.js:579:10)
app-frontend_1  |     at Module.load (module.js:487:32)
app-frontend_1  |     at tryModuleLoad (module.js:446:12)
app-frontend_1  |     at Function.Module._load (module.js:438:3)
app-frontend_1  |     at Module.require (module.js:497:17)
app-frontend_1  |     at require (internal/module.js:20:19)
app-frontend_1  |     at Object.<anonymous> (/usr/src/node_modules/sass-loader/index.js:4:12)
app-frontend_1  |  @ ./js/modeling/modeling.js 8:0-42
app-frontend_1  | Child extract-text-webpack-plugin:
app-frontend_1  |
app-frontend_1  |     ERROR in ENOENT: no such file or directory, scandir '/usr/src/node_modules/node-sass/vendor'
app-frontend_1  | Child html-webpack-plugin for "index.html":
app-frontend_1  |     chunk    {0} index.html 27.5 kB [rendered]
app-frontend_1  |         [0] ./~/html-webpack-plugin/lib/loader.js!./template.handlebars 13.9 kB {0} [built]
app-frontend_1  |         [1] ./~/handlebars/runtime.js 156 bytes {0} [built]
app-frontend_1  |         [2] ./~/handlebars/dist/cjs/handlebars.runtime.js 923 bytes {0} [built]
app-frontend_1  |         [3] ./~/handlebars/dist/cjs/handlebars/base.js 5.12 kB {0} [built]
app-frontend_1  |         [4] ./~/handlebars/dist/cjs/handlebars/utils.js 1.98 kB {0} [built]
app-frontend_1  |         [5] ./~/handlebars/dist/cjs/handlebars/safe-string.js 218 bytes {0} [built]
app-frontend_1  |         [6] ./~/handlebars/dist/cjs/handlebars/exception.js 706 bytes {0} [built]
app-frontend_1  |         [7] ./~/handlebars/dist/cjs/handlebars/runtime.js 4.49 kB {0} [built]
app-frontend_1  | webpack: Failed to compile.

**Comment by allnulled** [comment]
`npm rebuild node-sass`

Big up, man, big up. Thank you. Like... 7 hours (?) looking for the workaround. An odyssea where I added the `.babelrc`, added the `webpack.config.js`, reread the `react-create-app` documentation, and it says that version `3.0.1` has the `node-sass` support, you only need to install it.

Finally, after hours... tada! Working.
